export type {
  CnpjLookupInput,
  CnaeCompanySearchResult,
  CnaeLookupInput,
  CompanyByCnpj,
  CompanyPartner,
  EnrichedCompany,
  ProspectBusiness,
  ProspectBusinessSignal,
  ProspectingLeadPayload,
  ProspectingProvider,
  ProspectingSearchInput,
  ProspectingSearchResult,
  ProspectingSignalTone,
  ProspectingStatus,
} from "./prospecting";
